version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    ports: ["8001:8001"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile   
    environment:
      - VUE_APP_CESIUM_TOKEN=${VUE_APP_CESIUM_TOKEN}
    ports: ["8080:8080"]
    depends_on: [backend]
